image: greenjune/vtk2023

tasks:

    - name: run
      init: |
          cd /workspace
          apt-get update && sudo

    - name: install mamba 
      init: |
          cd /workspace
          wget "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
          bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/mambaforge && rm Mambaforge-$(uname)-$(uname -m).sh
          /workspace/mambaforge/bin/mamba init bash
          source ${HOME}/.bashrc
          python -m http.server 8000

    - name: retrieve references data
      command: |
          cd /workspace
          curl -L -o ref.tar.xz https://cloud.uni-konstanz.de/index.php/s/tob7NGo8w2CZXAR/download?file=filename.tar.xz
          tar -xf ref.tar.xz
          rm -rf ref.tar.xz

    - name: Install Nextflow & nf core
      command: |
          cd /workspace
          curl -s https://get.nextflow.io | bash
          sudo mv nextflow /bin/
          export PATH=/bin:$PATH
    
    - name: Install Nextflow & nf core
      command: |
          cd /workspace
          pip install nf-core
          
ports:
    - port: 8000
      onOpen: open-preview   

workspaceLocation: "/workspace"

vscode:
  extensions: # based on nf-core.nf-core-extensionpack
    - codezombiech.gitignore # Language support for .gitignore files
    - esbenp.prettier-vscode # Markdown/CommonMark linting and style checking for Visual Studio Code
    - mechatroner.rainbow-csv # Highlight columns in csv files in different colors
    - nextflow.nextflow # Nextflow syntax highlighting
    - oderwat.indent-rainbow # Highlight indentation level
    - streetsidesoftware.code-spell-checker # Spelling checker for source code
    - REditorSupport.r
    - quarto.quarto
