image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      # Install Nextflow
      curl -s https://get.nextflow.io | bash
      mv nextflow $HOME/bin
      export PATH=$HOME/bin:$PATH

      # Install R
      sudo apt-get update
      sudo apt-get install -y r-base

  - command: |
      # Verify Nextflow and R installation
      nextflow -version
      R --version

ports:
  - port: 8888
    onOpen: open-preview
