image:
  file: .gitpod.Dockerfile

tasks:
    - name: run
      command: |
          apt-get update && sudo
    - name: Install R
      command: |
          sudo apt-get update
          sudo apt-get install -y r-base
     
    - name: Install Nextflow & nf core
      command: |
          curl -s https://get.nextflow.io | bash
          sudo mv nextflow /bin/
          export PATH=/bin:$PATH
          pip install nf-core


ports:
  - port: 8888
    onOpen: open-preview
