image: nfcore/gitpod:latest
tasks:
  - name: Install R
    init: |
      # Update package list
      sudo apt-get update
      
      # Install R
      sudo apt-get install -y r-base
      
      # Create a directory for user-specific R packages
      mkdir -p ~/.R/library
      
      # Set the R_LIBS_USER environment variable to the user-specific package directory
      export R_LIBS_USER=~/.R/library
      
      # Install the 'languageserver' R package
      R -e 'install.packages("languageserver", repos="https://cloud.r-project.org/")'

vscode:
  extensions:
    - codezombiech.gitignore # Language support for .gitignore files
    - esbenp.prettier-vscode # Markdown/CommonMark linting and style checking for Visual Studio Code
    - eamodio.gitlens # Quickly glimpse into whom, why, and when a line or code block was changed
    - EditorConfig.EditorConfig # override user/workspace settings with settings found in .editorconfig files
    - mechatroner.rainbow-csv # Highlight columns in csv files in different colors
    - nextflow.nextflow # Nextflow syntax highlighting
    - oderwat.indent-rainbow # Highlight indentation level
    - streetsidesoftware.code-spell-checker # Spelling checker for source code
    - REditorSupport.r
    - quarto.quarto